services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    restart: always
    networks:
      - server_network
    
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - server_db
    env_file:
      - .env
    restart: always
    
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes: 
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - server_db
      - server_network
    env_file:
      - .env

networks:
  server_network:
    driver: bridge
    name: server_network
  server_db:
    driver: bridge
    name: server_db

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: volumes
      device: /home/nwattana/data/wp
      o: bind
  
  mariadb_data:
    driver: local
    driver_opts:
      type: volumes
      device: /home/nwattana/data/db
      o: bind
